In [32]:
import numpy as np
import torch
import torch.nn.functional as F

Batch = 12

KV = torch.randn(size=(1, 16, 1, 513))
Q = torch.randn(size=(1, 513, 128)).repeat(16,1,1)
    
def softmax_then_matmul(KV, Q, atten。、tion_mask):
    KV = KV + attention_mask
    import pdb;pdb.set_trace()
    KV = F.softmax(KV, dim=-1).squeeze(0)
    res = torch.matmul(KV, Q)
    print(KV)
    return KV

attention_mask = torch.FloatTensor([-10000]*500 + [0]*13).reshape(1,1,1,513)
expected = softmax_then_matmul(KV, Q, attention_mask)
# np.allclose(expected, actual)

> /tmp/ipykernel_3715917/172156229.py(13)softmax_then_matmul()
     11     KV = KV + attention_mask
     12     import pdb;pdb.set_trace()
---> 13     KV = F.softmax(KV, dim=-1).squeeze(0)
     14     res = torch.matmul(KV, Q)
     15     print(KV)



ipdb>  KV


tensor([[[[-9.9997e+03, -1.0002e+04, -1.0002e+04,  ..., -3.5008e-02,
            8.5505e-03, -1.0970e+00]],

         [[-9.9996e+03, -9.9998e+03, -1.0001e+04,  ...,  5.0934e-01,
            2.6110e-01, -1.4054e+00]],

         [[-9.9992e+03, -1.0000e+04, -9.9994e+03,  ...,  9.8569e-01,
            1.2394e+00, -7.4308e-01]],

         ...,

         [[-9.9993e+03, -1.0001e+04, -1.0000e+04,  ..., -3.8851e-02,
            4.8023e-02, -2.0115e+00]],

         [[-1.0001e+04, -9.9996e+03, -1.0001e+04,  ..., -8.8392e-01,
           -6.5494e-02,  1.1873e+00]],

         [[-9.9993e+03, -1.0000e+04, -1.0001e+04,  ...,  1.0967e+00,
            4.1682e-01, -1.4942e+00]]]])


ipdb>  KV[0]


tensor([[[-9.9997e+03, -1.0002e+04, -1.0002e+04,  ..., -3.5008e-02,
           8.5505e-03, -1.0970e+00]],

        [[-9.9996e+03, -9.9998e+03, -1.0001e+04,  ...,  5.0934e-01,
           2.6110e-01, -1.4054e+00]],

        [[-9.9992e+03, -1.0000e+04, -9.9994e+03,  ...,  9.8569e-01,
           1.2394e+00, -7.4308e-01]],

        ...,

        [[-9.9993e+03, -1.0001e+04, -1.0000e+04,  ..., -3.8851e-02,
           4.8023e-02, -2.0115e+00]],

        [[-1.0001e+04, -9.9996e+03, -1.0001e+04,  ..., -8.8392e-01,
          -6.5494e-02,  1.1873e+00]],

        [[-9.9993e+03, -1.0000e+04, -1.0001e+04,  ...,  1.0967e+00,
           4.1682e-01, -1.4942e+00]]])


ipdb>  KV[0].shape


torch.Size([16, 1, 513])


ipdb>  KV[0,0].shape


torch.Size([1, 513])


ipdb>  KV[0,0]


tensor([[-9.9997e+03, -1.0002e+04, -1.0002e+04, -9.9991e+03, -1.0001e+04,
         -1.0001e+04, -1.0001e+04, -9.9985e+03, -1.0000e+04, -9.9998e+03,
         -9.9995e+03, -1.0001e+04, -9.9998e+03, -9.9993e+03, -9.9994e+03,
         -9.9997e+03, -1.0001e+04, -1.0000e+04, -1.0000e+04, -9.9986e+03,
         -1.0000e+04, -1.0001e+04, -9.9976e+03, -1.0001e+04, -9.9996e+03,
         -9.9991e+03, -1.0002e+04, -1.0000e+04, -9.9996e+03, -1.0001e+04,
         -1.0000e+04, -1.0002e+04, -1.0001e+04, -1.0000e+04, -1.0000e+04,
         -1.0001e+04, -9.9990e+03, -1.0000e+04, -1.0000e+04, -9.9993e+03,
         -1.0000e+04, -9.9996e+03, -9.9979e+03, -1.0003e+04, -1.0001e+04,
         -9.9985e+03, -9.9987e+03, -1.0002e+04, -9.9985e+03, -1.0002e+04,
         -1.0000e+04, -9.9999e+03, -1.0002e+04, -1.0000e+04, -9.9996e+03,
         -9.9994e+03, -1.0000e+04, -1.0001e+04, -9.9997e+03, -1.0002e+04,
         -9.9978e+03, -1.0002e+04, -1.0000e+04, -9.9999e+03, -9.9993e+03,
         -9.9997e+03, -9.9994e+03, -9.

ipdb>  F.softmax(KV[0,0],dim=-1)


tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

ipdb>  F.softmax(KV, dim=-1).squeeze(0)


tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0958, 0.1001, 0.0331]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.1108, 0.0865, 0.0163]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.1465, 0.1889, 0.0260]],

        ...,

        [[0.0000, 0.0000, 0.0000,  ..., 0.0286, 0.0312, 0.0040]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0239, 0.0543, 0.1900]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.1602, 0.0812, 0.0120]]])


ipdb>  q


In [30]:
attention_mask = torch.FloatTensor([0]*13 + [-10000]*500).reshape(1,1,1,513)
expected = softmax_then_matmul(KV, Q, attention_mask)

tensor([[[0.0649, 0.0211, 0.1022,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0542, 0.1968, 0.1005,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0540, 0.1360, 0.0050,  ..., 0.0000, 0.0000, 0.0000]],

        ...,

        [[0.0855, 0.0753, 0.0520,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0167, 0.0283, 0.0369,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.1272, 0.0336, 0.2070,  ..., 0.0000, 0.0000, 0.0000]]])


In [31]:
expected[0,0,:13]

tensor([0.0649, 0.0211, 0.1022, 0.0064, 0.1343, 0.0219, 0.0467, 0.0747, 0.0915,
        0.0084, 0.0832, 0.1890, 0.1557])

In [2]:
%time softmax_then_matmul(S, V)

CPU times: user 70 µs, sys: 120 µs, total: 190 µs
Wall time: 150 µs


array([[0.69450367, 0.64144421]])

In [3]:
%time increasing_softmax_then_matmul(S, V)

CPU times: user 86 µs, sys: 146 µs, total: 232 µs
Wall time: 241 µs


array([[0.69450367, 0.64144421]])