In [52]:
import torch
import numpy as np
import torch.nn.functional as F

In [53]:
input_ids = torch.LongTensor([[1,2,3,4,5,5,5]])
scores = torch.randn(1,7)

In [54]:
scores

tensor([[-0.1534,  0.8089,  0.8125, -0.0808, -0.7130, -1.2821,  0.4892]])

In [55]:
F.softmax(scores, dim=-1)

tensor([[0.0988, 0.2588, 0.2597, 0.1063, 0.0565, 0.0320, 0.1879]])

In [56]:
penalty = 1.25

score = torch.gather(scores, 1, input_ids)
print(score)

# if score < 0 then repetition penalty has to be multiplied to reduce the previous token probability
score = torch.where(score < 0, score * penalty, score / penalty)
print(score)

F.softmax(scores.scatter_(1, input_ids, score))

/tmp/ipykernel_3133427/3932079670.py:8: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(scores.scatter_(1, input_ids, score))


tensor([[0.1096, 0.2440, 0.2447, 0.1154, 0.0524, 0.0257, 0.2083]])

In [58]:
score

tensor([[ 0.6472,  0.6500, -0.1010, -0.8913, -1.6026, -1.6026, -1.6026]])

In [57]:
score

tensor([[ 0.6472,  0.6500, -0.1010, -0.8913, -1.6026, -1.6026, -1.6026]])