In [ ]:
import numpy as np

def create_input(shape):
    n, c ,h, w = shape
    inputs = []
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    inputs.append(f"n{i}_c{j}_h{k}_w{l}")     
    return np.array(inputs)
    
def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
     
    m = (n_stride//tn_stride)
    print(m)
    tensor = np.zeros(n * c * h * w * m, dtype='<U11')
    print(tensor.shape)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    
                    tensor[tensor_index] = arr[arr_index]
 
    return tensor

# ipt = np.arange(4*3*2*2) + 1
shape = (4,3,2,2)
stride = (24,4,2,1)

ipt = create_input(shape)
res = make_tensor(ipt,shape,stride)
print(ipt.reshape(-1,12))
print(res.reshape(-1,12))

In [30]:
import numpy as np

def create_input(shape):
    n, c ,h, w = shape
    inputs = []
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    inputs.append(f"n{i}_c{j}_h{k}_w{l}")     
    return np.array(inputs)
    
def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
     
    # m = (n_stride//tn_stride)
    # print(m)
    # tensor = np.zeros(n * c * h * w * m)
    tensor = np.zeros(n_stride * n)
    print(tensor.shape)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
 
    return tensor

ipt = np.arange(4*3*2*2) + 1
shape = (4,3,2,2)
stride = (48,12,4,1)

# ipt = create_input(shape)
res = make_tensor(ipt,shape,stride)
print(ipt.reshape(-1,12))
print(res.reshape(-1,12))

(192,)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]]
[[ 1.  2.  0.  0.  3.  4.  0.  0.  0.  0.  0.  0.]
 [ 5.  6.  0.  0.  7.  8.  0.  0.  0.  0.  0.  0.]
 [ 9. 10.  0.  0. 11. 12.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [13. 14.  0.  0. 15. 16.  0.  0.  0.  0.  0.  0.]
 [17. 18.  0.  0. 19. 20.  0.  0.  0.  0.  0.  0.]
 [21. 22.  0.  0. 23. 24.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [25. 26.  0.  0. 27. 28.  0.  0.  0.  0.  0.  0.]
 [29. 30.  0.  0. 31. 32.  0.  0.  0.  0.  0.  0.]
 [33. 34.  0.  0. 35. 36.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [37. 38.  0.  0. 39. 40.  0.  0.  0.  0.  0.  0.]
 [41. 42.  0.  0. 43. 44.  0.  0.  0.  0.  0.  0.]
 [45. 46.  0.  0. 47. 48.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [48]:
# save in local memory


def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
     
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
 
    return tensor

shape = (2,3,2,3)
n, c, h, w = shape
ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
stride = (9,9,3,1)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,3))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 0.  0.  0.]
 [19. 20. 21.]
 [22. 23. 24.]
 [ 0.  0.  0.]]
[[ 7.  8.  9.]
 [10. 11. 12.]
 [ 0.  0.  0.]
 [25. 26. 27.]
 [28. 29. 30.]
 [ 0.  0.  0.]]
[[13. 14. 15.]
 [16. 17. 18.]
 [ 0.  0.  0.]
 [31. 32. 33.]
 [34. 35. 36.]
 [ 0.  0.  0.]]


### case1 64-Bytes对齐存储方式

In [65]:
# save in local memory
import math


def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_aligned_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = w
    C_stride = math.ceil(h*w/16) * 16
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

# define shape & create input
shape = (2,3,4,5)
ipt = create_input(shape)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_aligned_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,8))
    print("="*50)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [61. 62. 63. 64. 65. 66. 67. 68.]
 [69. 70. 71. 72. 73. 74. 75. 76.]
 [77. 78. 79. 80.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 21.  22.  23.  24.  25.  26.  27.  28.]
 [ 29.  30.  31.  32.  33.  34.  35.  36.]
 [ 37.  38.  39.  40.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.]
 [ 89.  90.  91.  92.  93.  94.  95.  96.]
 [ 97.  98.  99. 100.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]
[[ 41.  42.  43.  44.  45.  46.  47.  48.]
 [ 49.  50.  51.  52.  53.  54.  55.  56.]
 [ 57.  58.  59.  60.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [101. 102. 103. 104. 105. 106. 107. 108.]
 [109. 110. 111. 112. 113. 114. 115. 116.]
 [117. 118. 119. 120.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


#### case2 紧凑存储方式

In [68]:
# save in local memory
import math


def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_compact_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = w
    C_stride = h*w
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

# define shape & create input
shape = (2,3,4,5)
ipt = create_input(shape)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_compact_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,8))
    print("="*50)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 61. 62. 63. 64.]
 [65. 66. 67. 68. 69. 70. 71. 72.]
 [73. 74. 75. 76. 77. 78. 79. 80.]]
[[ 21.  22.  23.  24.  25.  26.  27.  28.]
 [ 29.  30.  31.  32.  33.  34.  35.  36.]
 [ 37.  38.  39.  40.  81.  82.  83.  84.]
 [ 85.  86.  87.  88.  89.  90.  91.  92.]
 [ 93.  94.  95.  96.  97.  98.  99. 100.]]
[[ 41.  42.  43.  44.  45.  46.  47.  48.]
 [ 49.  50.  51.  52.  53.  54.  55.  56.]
 [ 57.  58.  59.  60. 101. 102. 103. 104.]
 [105. 106. 107. 108. 109. 110. 111. 112.]
 [113. 114. 115. 116. 117. 118. 119. 120.]]


#### case3 矩阵存储方式

In [82]:
# save in local memory
import math


def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_aligned_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = w
    C_stride = math.ceil(h*w/16) * 16
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

def matrix_reshape(shape, w=8):
    m,n = shape
    N=n
    C=math.ceil(m/w)
    H=1
    W=w
    return (N,C,H,W)

# define shape & create input
matrix_shape = (40,2)
shape = matrix_reshape(matrix_shape)
ipt = create_input(shape)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_aligned_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,8))
    print("="*50)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 9. 10. 11. 12. 13. 14. 15. 16.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[17. 18. 19. 20. 21. 22. 23. 24.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [57. 58. 59. 60. 61. 62. 63. 64.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[25. 26. 27. 28. 29. 30. 31. 32.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [65. 66. 67. 68. 69. 70. 71. 72.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[33. 34. 35. 36. 37. 38. 39. 40.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [73. 74. 75. 76. 77. 78. 79. 80.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


### case4 向量存储

In [83]:
# save in local memory
import math


def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_aligned_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = w
    C_stride = math.ceil(h*w/16) * 16
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

def vector_reshape(shape, w=8):
    m,n = shape
    N=n
    C=math.ceil(m/w)
    H=1
    W=w
    return (N,C,H,W)

# define shape & create input
matrix_shape = (40,1)
shape = matrix_reshape(matrix_shape)
ipt = create_input(shape)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_aligned_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,8))
    print("="*50)

[[1. 2. 3. 4. 5. 6. 7. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 9. 10. 11. 12. 13. 14. 15. 16.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[17. 18. 19. 20. 21. 22. 23. 24.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[25. 26. 27. 28. 29. 30. 31. 32.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[33. 34. 35. 36. 37. 38. 39. 40.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


####  case5 行对齐存储

In [5]:
# save in local memory
import math
import numpy as np

def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_aligned_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = math.ceil(w/16)*16
    C_stride = H_stride * h
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

# define shape & create input
shape = (2,3,4,5)
ipt = create_input(shape)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_aligned_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,8))
    print("="*50)

[[ 1.  2.  3.  4.  5.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  7.  8.  9. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [11. 12. 13. 14. 15.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [16. 17. 18. 19. 20.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [61. 62. 63. 64. 65.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [66. 67. 68. 69. 70.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [71. 72. 73. 74. 75.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [76. 77. 78. 79. 80.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 21.  22.  23.  24.  25.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 26.  27.  28.  29.  30.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 31.  32.  33.  34.  35.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 36.  37.  38.  39.  40.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 81.  82.  83.  84.  85.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 86.  8

### case6 64IC/32IC 存储 (FP32 1IC)

这个没太懂

首先是FP32遵循1IC的方式进行排列

先将w维数据全放上，再放h维的数据，之后将所有n维的全放上，最后再将c维数据放上（由于有64个NPU，c维按step=64递增）
事实上，这其实就是将kernel的shape当作(1,oc,ic,kh*kw)然后按照正常tensor的compact方式来排列的，因此为了方便，在bm1684x_coeff_arrange.cpp:ConvWeightArr函数中

ref:https://wiki.sophgo.com/pages/viewpage.action?pageId=52775719

上面那段话有点不好理解，我这里代码的实现方式还是

（64，64，3，3）--split--> (64,1,3,3) -->tpu_compact_aligned，

In [9]:
# save in local memory
import math
import numpy as np

def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_compact_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = w
    C_stride = h*w
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

# define shape & create input
shape = (8,3,3,3)
ipt = create_input(shape)

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_compact_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,9))
    print("="*50)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 28.  29.  30.  31.  32.  33.  34.  35.  36.]
 [ 55.  56.  57.  58.  59.  60.  61.  62.  63.]
 [ 82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [109. 110. 111. 112. 113. 114. 115. 116. 117.]
 [136. 137. 138. 139. 140. 141. 142. 143. 144.]
 [163. 164. 165. 166. 167. 168. 169. 170. 171.]
 [190. 191. 192. 193. 194. 195. 196. 197. 198.]]
[[ 10.  11.  12.  13.  14.  15.  16.  17.  18.]
 [ 37.  38.  39.  40.  41.  42.  43.  44.  45.]
 [ 64.  65.  66.  67.  68.  69.  70.  71.  72.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99.]
 [118. 119. 120. 121. 122. 123. 124. 125. 126.]
 [145. 146. 147. 148. 149. 150. 151. 152. 153.]
 [172. 173. 174. 175. 176. 177. 178. 179. 180.]
 [199. 200. 201. 202. 203. 204. 205. 206. 207.]]
[[ 19.  20.  21.  22.  23.  24.  25.  26.  27.]
 [ 46.  47.  48.  49.  50.  51.  52.  53.  54.]
 [ 73.  74.  75.  76.  77.  78.  79.  80.  81.]
 [100. 101. 102. 103. 104. 105. 106. 107. 108.]
 [127. 128. 129. 130. 131. 132. 133. 1

### case6 64IC/32IC 存储 (INT8 64IC)

* 真没有看懂
* 感觉64IC没啥不同啊，就是紧凑型排列

### cast6 3IC

In [ ]:
# save in local memory
import math
import numpy as np

def split(inputs, shape, npu_num=64):
    n,c,h,w = shape
    if c < npu_num:
        return [inputs[:,i:i+1] for i in range(c)], [(n,1,h,w) for i in range(c)]


def make_tensor(arr,shape,stride):
    arr = np.array(arr).flatten()
    n, c, h, w = shape 
    n_stride, c_stride, h_stride, w_stride = stride
    tn_stride = c * h * w
    
    tensor = np.zeros(n_stride * n)
    for i in range(n):
        for j in range(c):
            for k in range(h):
                for l in range(w):
                    # 计算当前元素在空间中的索引
                    tensor_index = i * n_stride + j * c_stride + k * h_stride + l * w_stride
                    # 计算当前元素应该在输入数组中的索引
                    arr_index = i * c * h * w + j * h * w + k * w + l
                    # 将当前元素从输入数组放置到空间中
                    tensor[tensor_index] = arr[arr_index]
    return tensor

def tpu_compact_stride(split_shape):
    n, c, h, w = split_shape
    W_stride = 1
    H_stride = w
    C_stride = h*w
    N_stride = C_stride * c
    return (N_stride, C_stride, H_stride, W_stride)
    
def create_input(shape):
    n, c, h, w = shape
    ipt = (np.arange(n*c*h*w) + 1).reshape(shape)
    return ipt

# define shape & create input
input_shape = (8,3,3,3)
ipt = create_input(shape)

weight_shape = (64,3,5,5)
stride_h = stride_w = 2

# split for npu
split_ipt_list, split_shape_list = split(ipt, shape)

# map input to tensor in tpu memory
for split_ipt, split_shape in zip(split_ipt_list, split_shape_list):
    print("="*50)
    stride = tpu_compact_stride(split_shape)
    tensor_in_npu = make_tensor(split_ipt,split_shape,stride)
    print(tensor_in_npu.reshape(-1,9))
    print("="*50)

In [1]:
import torch 
import torch.nn.functional as F

/home/chuyi/.local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [12]:
depthwise = torch.nn.Conv2d(3, 64, kernel_size=3, padding=[[0,0],[0,0],[2,2],[2,2]], groups=1)

input = torch.randn(4,3,224,224)
res = F.pad(input, (0,0,2,2), 'constant', 0)
res = depthwise(res)
# F.conv2d(input, weight=torch.zeros(64,3,4,4), kernel_size=4, padding=[[0,0],[0,0],[2,2],[2,2]], groups=1)

RuntimeError: expected padding to be a single integer value or a list of 2 values to match the convolution dimensions, but got padding=[0, 0, 1, 1]

In [25]:
depthwise = torch.nn.Conv2d(3, 64, kernel_size=3, padding=[[0,0],[0,0],[2,2],[2,2]], groups=3)

input = torch.randn(4,3,224,224)
F.conv2d(input, weight=torch.zeros(64,3,3,4), kernel_size=3, padding=[[0,0],[0,0],[2,2],[2,2]], group=1)

TypeError: conv2d() received an invalid combination of arguments - got (Tensor, group=int, padding=int, kernel_size=int, weight=Tensor), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)


In [21]:
depthwise.bias = torch.zeros(6)

TypeError: cannot assign 'torch.FloatTensor' as parameter 'bias' (torch.nn.Parameter or None expected)

In [22]:
depthwise.weight.shape

torch.Size([6, 1, 3, 3])

In [9]:
depthwise(torch.randn(1,3,16,16)).shape

torch.Size([1, 6, 224, 224])